//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PETC_Logsheet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PETC_LogsheetEntities : DbContext
    {
        public PETC_LogsheetEntities()
            : base("name=PETC_LogsheetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ACTIONS> TBL_ACTIONS { get; set; }
        public virtual DbSet<TBL_CEC> TBL_CEC { get; set; }
        public virtual DbSet<TBL_LOGSHEET_REMOTE> TBL_LOGSHEET_REMOTE { get; set; }
        public virtual DbSet<TBL_PETC> TBL_PETC { get; set; }
        public virtual DbSet<TBL_SUBORDINATE> TBL_SUBORDINATE { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TBL_LOGSHEET_INQUIRY> TBL_LOGSHEET_INQUIRY { get; set; }
    }
}
