//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PETC_Logsheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SUBORDINATE
    {
        public int ID { get; set; }
        public string SUB_CODE { get; set; }
        public string SUB_NAME { get; set; }
        public Nullable<System.DateTime> SUB_EXPIRY { get; set; }
    }
}
