//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PETC_Logsheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOGSHEET_REMOTE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LOG_REGDATE { get; set; }
        public string LOG_CONTROL { get; set; }
        public string LOG_PETCCODE { get; set; }
        public string LOG_RECEIVEDVIA { get; set; }
        public string LOG_REVEIDBY { get; set; }
        public string LOG_PRBRECEIVED { get; set; }
        public Nullable<System.DateTime> LOG_TMERECEIVED { get; set; }
        public string LOG_RMTBY { get; set; }
        public string LOG_ACTTAKEN { get; set; }
        public Nullable<System.DateTime> LOG_ACTDATE { get; set; }
        public string LOG_WRKSTATIONCODE { get; set; }
        public string LOG_CECNO { get; set; }
        public string LOG_REMARKS { get; set; }
        public Nullable<System.DateTime> LOG_RESPTIME { get; set; }
        public Nullable<System.DateTime> LOG_DATELOG { get; set; }
        public string LOG_REGISTRYCODE { get; set; }
    }
}
